// Idea Bank — Representative Image Generation
// Self-contained module: called by single-idea UI and (later) batch processing.

const IDEA_IMAGE_SOURCE_SIZE = '1024x1024';
const IDEA_IMAGE_MODEL = 'gpt-image-2';
const IDEA_IMAGE_PROXY_ENDPOINT = 'http://localhost:5001/api/images/generate';

const IDEA_IMAGE_PLACEHOLDERS = [
    'idea_title',
    'problem_or_opportunity',
    'solution_details',
    'potential_impact'
];

// Final display sizes. The largest is generated by cropping/scaling the source;
// the smaller two are derived by symmetric side-crops of the largest.
const IDEA_IMAGE_VARIANTS = [
    { key: 'large',  width: 197, height: 171 },
    { key: 'medium', width: 156, height: 171 },
    { key: 'small',  width: 116, height: 171 }
];

function substituteImagePromptPlaceholders(template, ideaData) {
    let out = String(template || '');
    IDEA_IMAGE_PLACEHOLDERS.forEach(key => {
        const value = (ideaData && ideaData[key] != null) ? String(ideaData[key]) : '';
        out = out.split(`{{${key}}}`).join(value);
    });
    return out;
}

async function callImageAPI(prompt, apiKey, size = IDEA_IMAGE_SOURCE_SIZE, model = IDEA_IMAGE_MODEL) {
    if (!apiKey) {
        throw new Error('Please enter an OpenAI API key to generate images.');
    }
    if (!prompt || !prompt.trim()) {
        throw new Error('Image prompt is empty.');
    }

    let response;
    try {
        response = await fetch(IDEA_IMAGE_PROXY_ENDPOINT, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                prompt: prompt,
                api_key: apiKey,
                size: size,
                model: model
            })
        });
    } catch (err) {
        throw new Error('Cannot connect to backend server. Please make sure the Flask server is running on http://localhost:5001');
    }

    if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || `Image API request failed: ${response.status} ${response.statusText}`);
    }
    const data = await response.json();
    if (!data.b64_json) {
        throw new Error('Image API returned no image data.');
    }
    return data.b64_json;
}

function loadImageFromBase64(b64) {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = () => resolve(img);
        img.onerror = () => reject(new Error('Failed to decode generated image.'));
        img.src = `data:image/png;base64,${b64}`;
    });
}

// Build the largest variant by center-cropping the source to the target aspect,
// then scaling to exactly target width x height. Returns the canvas.
function buildLargestVariantCanvas(sourceImage, targetWidth, targetHeight) {
    const srcW = sourceImage.naturalWidth;
    const srcH = sourceImage.naturalHeight;
    const targetAspect = targetWidth / targetHeight;
    const srcAspect = srcW / srcH;

    let cropW, cropH, cropX, cropY;
    if (srcAspect > targetAspect) {
        // Source too wide — crop sides.
        cropH = srcH;
        cropW = Math.round(srcH * targetAspect);
        cropY = 0;
        cropX = Math.round((srcW - cropW) / 2);
    } else {
        // Source too tall (or square) — crop top/bottom.
        cropW = srcW;
        cropH = Math.round(srcW / targetAspect);
        cropX = 0;
        cropY = Math.round((srcH - cropH) / 2);
    }

    const canvas = document.createElement('canvas');
    canvas.width = targetWidth;
    canvas.height = targetHeight;
    const ctx = canvas.getContext('2d');
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';
    ctx.drawImage(
        sourceImage,
        cropX, cropY, cropW, cropH,
        0, 0, targetWidth, targetHeight
    );
    return canvas;
}

// Side-crop the large canvas symmetrically to a narrower width (same height).
function buildSideCroppedCanvas(largeCanvas, targetWidth, targetHeight) {
    const trim = largeCanvas.width - targetWidth;
    const leftTrim = Math.floor(trim / 2);
    const canvas = document.createElement('canvas');
    canvas.width = targetWidth;
    canvas.height = targetHeight;
    const ctx = canvas.getContext('2d');
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';
    ctx.drawImage(
        largeCanvas,
        leftTrim, 0, targetWidth, targetHeight,
        0, 0, targetWidth, targetHeight
    );
    return canvas;
}

function canvasToPngB64(canvas) {
    // toDataURL returns "data:image/png;base64,...."; strip the prefix.
    const dataUrl = canvas.toDataURL('image/png');
    const commaIdx = dataUrl.indexOf(',');
    return commaIdx >= 0 ? dataUrl.slice(commaIdx + 1) : dataUrl;
}

async function deriveImageVariants(sourceB64) {
    const sourceImage = await loadImageFromBase64(sourceB64);
    const large = IDEA_IMAGE_VARIANTS.find(v => v.key === 'large');
    const medium = IDEA_IMAGE_VARIANTS.find(v => v.key === 'medium');
    const small = IDEA_IMAGE_VARIANTS.find(v => v.key === 'small');

    const largeCanvas = buildLargestVariantCanvas(sourceImage, large.width, large.height);
    const mediumCanvas = buildSideCroppedCanvas(largeCanvas, medium.width, medium.height);
    const smallCanvas = buildSideCroppedCanvas(largeCanvas, small.width, small.height);

    return {
        large:  canvasToPngB64(largeCanvas),
        medium: canvasToPngB64(mediumCanvas),
        small:  canvasToPngB64(smallCanvas)
    };
}

async function generateIdeaImageBundle(ideaData, template, apiKey, model = IDEA_IMAGE_MODEL) {
    const prompt = substituteImagePromptPlaceholders(template, ideaData);
    const sourceB64 = await callImageAPI(prompt, apiKey, IDEA_IMAGE_SOURCE_SIZE, model);
    const variants = await deriveImageVariants(sourceB64);
    return {
        prompt,
        source_b64: sourceB64,
        variants
    };
}
